spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: springboot-client
            client-secret: secret
            authorization-grant-type: password
            scope: openid, profile, email
        provider:
          keycloak:
            token-uri: http://localhost:8080/auth/realms/springboot-realm/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/auth/realms/springboot-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
