spring:
  application:
    name: OAuth
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://${KEYCLOAK_INTERNAL_HOST}:${KEYCLOAK_INTERNAL_PORT}/realms/${KEYCLOAK_REALM}

server:
  port: 8080

keycloak:
  realm: ${KEYCLOAK_REALM}
  url: http://${KEYCLOAK_INTERNAL_HOST}:${KEYCLOAK_INTERNAL_PORT}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
