server:
  port: ${OAUTH_INTERNAL_PORT:8080}
  servlet:
    context-path: /

keycloak:
  auth-server-url: ${OAUTH_INTERNAL_PROTOCOL:http}://${KEYCLOAK_INTERNAL_HOST:keycloak}:${KEYCLOAK_INTERNAL_API_PORT:8080}/auth
  realm: ${KEYCLOAK_REALM:constrsw}
  resource:
    client-id: ${KEYCLOAK_CLIENT_ID:oauth}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:wsNXUxaupU9X6jCncsn3rOEy6PDt7oJO}
  grant-type: ${KEYCLOAK_GRANT_TYPE:password}
  admin:
    username: ${KEYCLOAK_ADMIN:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:a12345678}

spring:
  application:
    name: oauth-service
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: ${KEYCLOAK_ADMIN:admin}
      password: ${KEYCLOAK_ADMIN_PASSWORD:a12345678}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /manage
  endpoint:
    health:
      show-details: always
      enabled: true
      probes:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.keycloak: WARN
    com.constrsw: DEBUG
  file:
    name: /var/log/oauth/application.log
    max-size: 10MB
    max-history: 7
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %logger{36} - %msg%n"